#!/bin/bash

export VIRTUALENV_DISTRIBUTE=true
export PIP_REQUIRE_VIRTUALENV=true
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

syspip() {
    PIP_REQUIRE_VIRTUALENV="" sudo pip "$@"
}

syspip3() {
    PIP_REQUIRE_VIRTUALENV="" sudo pip3 "$@"
}
